name: build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.*
      - name: Install dependencies
        run: dotnet restore -p:NuGetBuild=True
      - name: Add package
        id: add_package
        run: |
          pwd
          ls -hal .
          echo '----------'
          ls -hal ..
          echo '----------'
          ls -hal ~
